#![allow(non_snake_case)]

#[path = "AC1LegacyPStringBase.rs"]
pub mod AC1LegacyPStringBase;
#[path = "AC1LegacyString.rs"]
pub mod AC1LegacyString;
#[path = "ActionMapValue.rs"]
pub mod ActionMapValue;
#[path = "AmbientSTBDesc.rs"]
pub mod AmbientSTBDesc;
#[path = "AmbientSoundDesc.rs"]
pub mod AmbientSoundDesc;
#[path = "AnimData.rs"]
pub mod AnimData;
#[path = "AnimationFrame.rs"]
pub mod AnimationFrame;
#[path = "AnimationHook.rs"]
pub mod AnimationHook;
#[path = "AnimationPartChange.rs"]
pub mod AnimationPartChange;
#[path = "AttackCone.rs"]
pub mod AttackCone;
#[path = "AutoGrowHashTable.rs"]
pub mod AutoGrowHashTable;
#[path = "BSPTrees.rs"]
pub mod BSPTrees;
#[path = "BaseProperty.rs"]
pub mod BaseProperty;
#[path = "BasePropertyDesc.rs"]
pub mod BasePropertyDesc;
#[path = "BuildingInfo.rs"]
pub mod BuildingInfo;
#[path = "BuildingPortal.rs"]
pub mod BuildingPortal;
#[path = "CInputMap.rs"]
pub mod CInputMap;
#[path = "CellPortal.rs"]
pub mod CellPortal;
#[path = "CellStruct.rs"]
pub mod CellStruct;
#[path = "ChatEmoteData.rs"]
pub mod ChatEmoteData;
#[path = "CloObjectEffect.rs"]
pub mod CloObjectEffect;
#[path = "CloSubPalEffect.rs"]
pub mod CloSubPalEffect;
#[path = "CloSubPalette.rs"]
pub mod CloSubPalette;
#[path = "CloSubPaletteRange.rs"]
pub mod CloSubPaletteRange;
#[path = "CloTextureEffect.rs"]
pub mod CloTextureEffect;
#[path = "ClothingBaseEffect.rs"]
pub mod ClothingBaseEffect;
#[path = "ColorARGB.rs"]
pub mod ColorARGB;
#[path = "CombatManeuver.rs"]
pub mod CombatManeuver;
#[path = "Contract.rs"]
pub mod Contract;
#[path = "ControlSpecification.rs"]
pub mod ControlSpecification;
#[path = "CylSphere.rs"]
pub mod CylSphere;
#[path = "DBObj.rs"]
pub mod DBObj;
#[path = "DayGroup.rs"]
pub mod DayGroup;
#[path = "DeviceKeyMapEntry.rs"]
pub mod DeviceKeyMapEntry;
#[path = "ElementDesc.rs"]
pub mod ElementDesc;
#[path = "EnumMapperData.rs"]
pub mod EnumMapperData;
#[path = "EyeStripCG.rs"]
pub mod EyeStripCG;
#[path = "FaceStripCG.rs"]
pub mod FaceStripCG;
#[path = "FontCharDesc.rs"]
pub mod FontCharDesc;
#[path = "Frame.rs"]
pub mod Frame;
#[path = "GameTime.rs"]
pub mod GameTime;
#[path = "GearCG.rs"]
pub mod GearCG;
#[path = "GfxObjInfo.rs"]
pub mod GfxObjInfo;
#[path = "HairStyleCG.rs"]
pub mod HairStyleCG;
#[path = "HashTable.rs"]
pub mod HashTable;
#[path = "HeritageGroupCG.rs"]
pub mod HeritageGroupCG;
#[path = "InputsConflictsValue.rs"]
pub mod InputsConflictsValue;
#[path = "IntrusiveHashTable.rs"]
pub mod IntrusiveHashTable;
#[path = "LandDefs.rs"]
pub mod LandDefs;
#[path = "LandSurf.rs"]
pub mod LandSurf;
#[path = "LightInfo.rs"]
pub mod LightInfo;
#[path = "LocationType.rs"]
pub mod LocationType;
#[path = "MaterialProperty.rs"]
pub mod MaterialProperty;
#[path = "MediaDesc.rs"]
pub mod MediaDesc;
#[path = "MediaDescAlpha.rs"]
pub mod MediaDescAlpha;
#[path = "MediaDescAnimation.rs"]
pub mod MediaDescAnimation;
#[path = "MediaDescCursor.rs"]
pub mod MediaDescCursor;
#[path = "MediaDescFade.rs"]
pub mod MediaDescFade;
#[path = "MediaDescImage.rs"]
pub mod MediaDescImage;
#[path = "MediaDescJump.rs"]
pub mod MediaDescJump;
#[path = "MediaDescMessage.rs"]
pub mod MediaDescMessage;
#[path = "MediaDescMovie.rs"]
pub mod MediaDescMovie;
#[path = "MediaDescPause.rs"]
pub mod MediaDescPause;
#[path = "MediaDescSound.rs"]
pub mod MediaDescSound;
#[path = "MediaDescState.rs"]
pub mod MediaDescState;
#[path = "MotionCommandData.rs"]
pub mod MotionCommandData;
#[path = "MotionData.rs"]
pub mod MotionData;
#[path = "NameFilterLanguageData.rs"]
pub mod NameFilterLanguageData;
#[path = "ObfuscatedPStringBase.rs"]
pub mod ObfuscatedPStringBase;
#[path = "ObjDesc.rs"]
pub mod ObjDesc;
#[path = "ObjHierarchyNode.rs"]
pub mod ObjHierarchyNode;
#[path = "ObjectDesc.rs"]
pub mod ObjectDesc;
#[path = "PHashTable.rs"]
pub mod PHashTable;
#[path = "PStringBase.rs"]
pub mod PStringBase;
#[path = "PackableHashTable.rs"]
pub mod PackableHashTable;
#[path = "PackedQualifiedDataId.rs"]
pub mod PackedQualifiedDataId;
#[path = "PhysicsScriptData.rs"]
pub mod PhysicsScriptData;
#[path = "PhysicsScriptTableData.rs"]
pub mod PhysicsScriptTableData;
#[path = "Polygon.rs"]
pub mod Polygon;
#[path = "PortalRef.rs"]
pub mod PortalRef;
#[path = "Position.rs"]
pub mod Position;
#[path = "QualifiedControl.rs"]
pub mod QualifiedControl;
#[path = "QualifiedDataId.rs"]
pub mod QualifiedDataId;
#[path = "RegionMisc.rs"]
pub mod RegionMisc;
#[path = "RoadAlphaMap.rs"]
pub mod RoadAlphaMap;
#[path = "SWVertex.rs"]
pub mod SWVertex;
#[path = "SceneDesc.rs"]
pub mod SceneDesc;
#[path = "SceneType.rs"]
pub mod SceneType;
#[path = "ScriptAndModData.rs"]
pub mod ScriptAndModData;
#[path = "Season.rs"]
pub mod Season;
#[path = "SexCG.rs"]
pub mod SexCG;
#[path = "SkillBase.rs"]
pub mod SkillBase;
#[path = "SkillCG.rs"]
pub mod SkillCG;
#[path = "SkillFormula.rs"]
pub mod SkillFormula;
#[path = "SkyDesc.rs"]
pub mod SkyDesc;
#[path = "SkyObject.rs"]
pub mod SkyObject;
#[path = "SkyObjectReplace.rs"]
pub mod SkyObjectReplace;
#[path = "SkyTimeOfDay.rs"]
pub mod SkyTimeOfDay;
#[path = "SoundData.rs"]
pub mod SoundData;
#[path = "SoundDesc.rs"]
pub mod SoundDesc;
#[path = "SoundEntry.rs"]
pub mod SoundEntry;
#[path = "SoundHashData.rs"]
pub mod SoundHashData;
#[path = "SpellBase.rs"]
pub mod SpellBase;
#[path = "SpellComponentBase.rs"]
pub mod SpellComponentBase;
#[path = "SpellSet.rs"]
pub mod SpellSet;
#[path = "SpellSetTiers.rs"]
pub mod SpellSetTiers;
#[path = "Sphere.rs"]
pub mod Sphere;
#[path = "Stab.rs"]
pub mod Stab;
#[path = "StartingArea.rs"]
pub mod StartingArea;
#[path = "StateDesc.rs"]
pub mod StateDesc;
#[path = "StringInfo.rs"]
pub mod StringInfo;
#[path = "StringInfoBaseProperty.rs"]
pub mod StringInfoBaseProperty;
#[path = "StringTableData.rs"]
pub mod StringTableData;
#[path = "StringTableString.rs"]
pub mod StringTableString;
#[path = "TMTerrainDesc.rs"]
pub mod TMTerrainDesc;
#[path = "TabooTableEntry.rs"]
pub mod TabooTableEntry;
#[path = "TemplateCG.rs"]
pub mod TemplateCG;
#[path = "TerrainAlphaMap.rs"]
pub mod TerrainAlphaMap;
#[path = "TerrainDesc.rs"]
pub mod TerrainDesc;
#[path = "TerrainInfo.rs"]
pub mod TerrainInfo;
#[path = "TerrainTex.rs"]
pub mod TerrainTex;
#[path = "TerrainType.rs"]
pub mod TerrainType;
#[path = "TexMerge.rs"]
pub mod TexMerge;
#[path = "TimeOfDay.rs"]
pub mod TimeOfDay;
#[path = "UserBindingData.rs"]
pub mod UserBindingData;
#[path = "Vec2Duv.rs"]
pub mod Vec2Duv;
#[path = "VertexArray.rs"]
pub mod VertexArray;
