#![allow(non_snake_case)]

#[path = "AC1LegacyString.rs"]
pub mod AC1LegacyString;
#[path = "AnimationHook.rs"]
pub mod AnimationHook;
#[path = "AnimationFrame.rs"]
pub mod AnimationFrame;
#[path = "AnimationPartChange.rs"]
pub mod AnimationPartChange;
#[path = "AmbientSoundDesc.rs"]
pub mod AmbientSoundDesc;
#[path = "AmbientSTBDesc.rs"]
pub mod AmbientSTBDesc;
#[path = "AnimData.rs"]
pub mod AnimData;
#[path = "AttackCone.rs"]
pub mod AttackCone;
#[path = "BSPTrees.rs"]
pub mod BSPTrees;
#[path = "ColorARGB.rs"]
pub mod ColorARGB;
#[path = "CylSphere.rs"]
pub mod CylSphere;
#[path = "DayGroup.rs"]
pub mod DayGroup;
#[path = "DBObj.rs"]
pub mod DBObj;
#[path = "EyeStripCG.rs"]
pub mod EyeStripCG;
#[path = "FaceStripCG.rs"]
pub mod FaceStripCG;
#[path = "Frame.rs"]
pub mod Frame;
#[path = "GameTime.rs"]
pub mod GameTime;
#[path = "GearCG.rs"]
pub mod GearCG;
#[path = "HairStyleCG.rs"]
pub mod HairStyleCG;
#[path = "HashTable.rs"]
pub mod HashTable;
#[path = "HeritageGroupCG.rs"]
pub mod HeritageGroupCG;
#[path = "LandDefs.rs"]
pub mod LandDefs;
#[path = "LandSurf.rs"]
pub mod LandSurf;
#[path = "LightInfo.rs"]
pub mod LightInfo;
#[path = "LocationType.rs"]
pub mod LocationType;
#[path = "MotionCommandData.rs"]
pub mod MotionCommandData;
#[path = "MotionData.rs"]
pub mod MotionData;
#[path = "ObjDesc.rs"]
pub mod ObjDesc;
#[path = "ObjectDesc.rs"]
pub mod ObjectDesc;
#[path = "PackedQualifiedDataId.rs"]
pub mod PackedQualifiedDataId;
#[path = "PhysicsScriptData.rs"]
pub mod PhysicsScriptData;
#[path = "PhysicsScriptTableData.rs"]
pub mod PhysicsScriptTableData;
#[path = "PortalRef.rs"]
pub mod PortalRef;
#[path = "Polygon.rs"]
pub mod Polygon;
#[path = "Position.rs"]
pub mod Position;
#[path = "QualifiedDataId.rs"]
pub mod QualifiedDataId;
#[path = "RegionMisc.rs"]
pub mod RegionMisc;
#[path = "RoadAlphaMap.rs"]
pub mod RoadAlphaMap;
#[path = "SceneDesc.rs"]
pub mod SceneDesc;
#[path = "SceneType.rs"]
pub mod SceneType;
#[path = "ScriptAndModData.rs"]
pub mod ScriptAndModData;
#[path = "Season.rs"]
pub mod Season;
#[path = "SexCG.rs"]
pub mod SexCG;
#[path = "SkillCG.rs"]
pub mod SkillCG;
#[path = "SkyDesc.rs"]
pub mod SkyDesc;
#[path = "SkyObject.rs"]
pub mod SkyObject;
#[path = "SkyObjectReplace.rs"]
pub mod SkyObjectReplace;
#[path = "SkyTimeOfDay.rs"]
pub mod SkyTimeOfDay;
#[path = "SoundDesc.rs"]
pub mod SoundDesc;
#[path = "SoundData.rs"]
pub mod SoundData;
#[path = "SoundEntry.rs"]
pub mod SoundEntry;
#[path = "SoundHashData.rs"]
pub mod SoundHashData;
#[path = "Sphere.rs"]
pub mod Sphere;
#[path = "StartingArea.rs"]
pub mod StartingArea;
#[path = "SWVertex.rs"]
pub mod SWVertex;
#[path = "TemplateCG.rs"]
pub mod TemplateCG;
#[path = "TexMerge.rs"]
pub mod TexMerge;
#[path = "TerrainAlphaMap.rs"]
pub mod TerrainAlphaMap;
#[path = "TerrainDesc.rs"]
pub mod TerrainDesc;
#[path = "TerrainTex.rs"]
pub mod TerrainTex;
#[path = "TerrainType.rs"]
pub mod TerrainType;
#[path = "TimeOfDay.rs"]
pub mod TimeOfDay;
#[path = "TMTerrainDesc.rs"]
pub mod TMTerrainDesc;
#[path = "Vec2Duv.rs"]
pub mod Vec2Duv;
#[path = "VertexArray.rs"]
pub mod VertexArray;
