#![allow(non_snake_case)]

#[path = "Animation.rs"]
pub mod Animation;
#[path = "CharGen.rs"]
pub mod CharGen;
#[path = "ClothingTable.rs"]
pub mod ClothingTable;
#[path = "CombatTable.rs"]
pub mod CombatTable;
#[path = "GfxObj.rs"]
pub mod GfxObj;
#[path = "Iteration.rs"]
pub mod Iteration;
#[path = "LanguageString.rs"]
pub mod LanguageString;
#[path = "MotionTable.rs"]
pub mod MotionTable;
#[path = "PalSet.rs"]
pub mod PalSet;
#[path = "Palette.rs"]
pub mod Palette;
#[path = "ParticleEmitter.rs"]
pub mod ParticleEmitter;
#[path = "PhysicsScript.rs"]
pub mod PhysicsScript;
#[path = "PhysicsScriptTable.rs"]
pub mod PhysicsScriptTable;
#[path = "Region.rs"]
pub mod Region;
#[path = "RenderSurface.rs"]
pub mod RenderSurface;
#[path = "Scene.rs"]
pub mod Scene;
#[path = "Setup.rs"]
pub mod Setup;
#[path = "SoundTable.rs"]
pub mod SoundTable;
#[path = "StringTable.rs"]
pub mod StringTable;
#[path = "Surface.rs"]
pub mod Surface;
#[path = "SurfaceTexture.rs"]
pub mod SurfaceTexture;
#[path = "Wave.rs"]
pub mod Wave;
