#![allow(non_snake_case)]

#[path = "ActionMap.rs"]
pub mod ActionMap;
#[path = "Animation.rs"]
pub mod Animation;
#[path = "BadDataTable.rs"]
pub mod BadDataTable;
#[path = "CharGen.rs"]
pub mod CharGen;
#[path = "ChatPoseTable.rs"]
pub mod ChatPoseTable;
#[path = "ClothingTable.rs"]
pub mod ClothingTable;
#[path = "CombatTable.rs"]
pub mod CombatTable;
#[path = "ContractTable.rs"]
pub mod ContractTable;
#[path = "DualEnumIDMap.rs"]
pub mod DualEnumIDMap;
#[path = "EnumIDMap.rs"]
pub mod EnumIDMap;
#[path = "EnumMapper.rs"]
pub mod EnumMapper;
#[path = "EnvCell.rs"]
pub mod EnvCell;
#[path = "Environment.rs"]
pub mod Environment;
#[path = "ExperienceTable.rs"]
pub mod ExperienceTable;
#[path = "Font.rs"]
pub mod Font;
#[path = "GfxObj.rs"]
pub mod GfxObj;
#[path = "GfxObjDegradeInfo.rs"]
pub mod GfxObjDegradeInfo;
#[path = "Iteration.rs"]
pub mod Iteration;
#[path = "LandBlock.rs"]
pub mod LandBlock;
#[path = "LandBlockInfo.rs"]
pub mod LandBlockInfo;
#[path = "LanguageInfo.rs"]
pub mod LanguageInfo;
#[path = "LanguageString.rs"]
pub mod LanguageString;
#[path = "MasterInputMap.rs"]
pub mod MasterInputMap;
#[path = "MasterProperty.rs"]
pub mod MasterProperty;
#[path = "MaterialInstance.rs"]
pub mod MaterialInstance;
#[path = "MaterialModifier.rs"]
pub mod MaterialModifier;
#[path = "MotionTable.rs"]
pub mod MotionTable;
#[path = "NameFilterTable.rs"]
pub mod NameFilterTable;
#[path = "ObjectHierarchy.rs"]
pub mod ObjectHierarchy;
#[path = "PalSet.rs"]
pub mod PalSet;
#[path = "Palette.rs"]
pub mod Palette;
#[path = "ParticleEmitter.rs"]
pub mod ParticleEmitter;
#[path = "PhysicsScript.rs"]
pub mod PhysicsScript;
#[path = "PhysicsScriptTable.rs"]
pub mod PhysicsScriptTable;
#[path = "QualityFilter.rs"]
pub mod QualityFilter;
#[path = "Region.rs"]
pub mod Region;
#[path = "RenderMaterial.rs"]
pub mod RenderMaterial;
#[path = "RenderSurface.rs"]
pub mod RenderSurface;
#[path = "RenderTexture.rs"]
pub mod RenderTexture;
#[path = "Scene.rs"]
pub mod Scene;
#[path = "Setup.rs"]
pub mod Setup;
#[path = "SkillTable.rs"]
pub mod SkillTable;
#[path = "SoundTable.rs"]
pub mod SoundTable;
#[path = "SpellComponentTable.rs"]
pub mod SpellComponentTable;
#[path = "SpellTable.rs"]
pub mod SpellTable;
#[path = "StringTable.rs"]
pub mod StringTable;
#[path = "Surface.rs"]
pub mod Surface;
#[path = "SurfaceTexture.rs"]
pub mod SurfaceTexture;
#[path = "TabooTable.rs"]
pub mod TabooTable;
#[path = "VitalTable.rs"]
pub mod VitalTable;
#[path = "Wave.rs"]
pub mod Wave;
